# Generated by Django 6.0.6 on 2026-09-07 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_merge_20260907_0702'),
        ('property', '0025_remove_complianceandcertification_shared_with'),
        ('tenant', '0013_alter_maintenancerequest_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='property.tenant'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['organisation', 'provider', 'is_default'], name='tenant_paym_organis_a8ee52_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organisation__isnull', True), ('tenant__isnull', False)), models.Q(('organisation__isnull', False), ('tenant__isnull', True)), _connector='OR'), name='payment_method_exactly_one_owner'),
        ),
    ]
