# Generated by Django 6.0.6 on 2026-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0014_paymentmethod_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='card_exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
