# Generated by Django 6.0.6 on 2026-09-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0015_paymentmethod_card_exp_month_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processedwebhookevent',
            name='tenant_proc_provide_9126c2_idx',
        ),
        migrations.RemoveConstraint(
            model_name='processedwebhookevent',
            name='unique_provider_event',
        ),
        migrations.DeleteModel(
            name='ProcessedWebhookEvent',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider_mandate_id',
        ),
    ]
