# Generated by Django 6.0.6 on 2026-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
