# Generated by Django 6.0.6 on 2026-06-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_complianceandcertification'),
        ('property', '0002_tenant_tenantdocument'),
    ]

    operations = [
    ]
