# Generated by Django 6.0.6 on 2026-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_merge_20260619_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='electrical_safety_certificate',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='epc',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='fire_risk_assessment',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='gas_safety_certificate',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='hmo_licence',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='insurance_documents',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='legionella_assessment',
        ),
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='pat_testing',
        ),
        migrations.AddField(
            model_name='complianceandcertification',
            name='certificate_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
