# Generated by Django 6.0.6 on 2026-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('property', '0005_uploaddocument_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='mortgage_documents',
            field=models.ManyToManyField(blank=True, related_name='mortgages', to='common.documentfile'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/'),
        ),
    ]
