# Generated by Django 6.0.6 on 2026-06-23 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_documentfile'),
        ('property', '0005_rename_notes_mortgage_broker_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('document_category', models.CharField(blank=True, choices=[('MORTGAGE_DOCUMENTS', 'Mortgage Documents'), ('TENANCY_AGREEMENT', 'Tenancy Agreement'), ('CERTIFICATE', 'Certificate'), ('INSURANCE', 'Insurance'), ('INVOICE', 'Invoice'), ('TAX_DOCUMENT', 'Tax Document'), ('PROPERTY_PHOTO', 'Property Photo'), ('LEGAL_DOCUMENT', 'Legal Document')], max_length=50, null=True)),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('files', models.ManyToManyField(blank=True, related_name='upload_documents', to='common.documentfile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_documents', to='property.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
