# Generated by Django 6.0.6 on 2026-07-01 06:45

import apps.property.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_uploaddocument_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.property.utils.tenant_avatar_upload_path),
        ),
    ]
