# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_tenant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tenants', to='property.property'),
        ),
    ]
