from django.urls import path
from api.views.property import (
    PropertyListCreateAPIView,
    PropertyRetrieveUpdateDestroyAPIView,
    MortgageListCreateAPIView,
    MortgageRetrieveAPIView,
    TenantRetrieveAPIView,
    TenantListCreateAPIView,
    TenantDocumentListCreateAPIView,
    TenantDocumentRetrieveAPIView
)

urlpatterns = [
    path(
        "proprty/",
        PropertyListCreateAPIView.as_view(),
        name="property-list-create"
    ),
    path(
        "proprty/<uuid:alias>/",
        PropertyRetrieveUpdateDestroyAPIView.as_view(),
        name="property-retrieve-update"
    ),
    path(
        "mortgage/",
        MortgageListCreateAPIView.as_view(),
        name="mortgage-list-create"
    ),
    path(
        "mortgage/<uuid:alias>/",
        MortgageRetrieveAPIView.as_view(),
        name="mortgage-retrieve-update"
    ),
    path(
        "tenants/",
        TenantListCreateAPIView.as_view(),
        name="tenant-list-create"
    ),
    path(
        "tenants/<uuid:alias>/",
        TenantRetrieveAPIView.as_view(),
        name="tenant-retrieve-update"
    ),
    path(""
         "tenants/<uuid:alias>/documents/",
         TenantDocumentListCreateAPIView.as_view(),
         name="tenant-document-list-create"
    ),
    path(
        "tenants/<uuid:alias>/documents/<uuid:document_alias>/",
        TenantDocumentRetrieveAPIView.as_view(),
        name="tenant-document-detail"
    ),
]