from django.urls import path

from api.views.tenants import (
    PaymentMethodListCreateView,
    PaymentMethodDetailView,
    RentPaymentListCreateView,
    RentPaymentDetailView,
    RentBalanceSummaryView,
    RentStatementView,
    FinancialOverviewListView,
    PropertyTenancyListView,
    PaymentHistoryView,
    MaintenanceRequestListCreateAPIView,
    MaintenanceRequestRetrieveUpdateDestroyAPIView,
    MaintenanceRequestCommentListCreateView,
    MaintenanceRequestCommentRetrieveUpdateDestroyView,
    TenantSharedComplianceListView,
    TenantListAPiView,
)

urlpatterns = [
    path(
        "/payment-methods",
        PaymentMethodListCreateView.as_view(),
        name="payment-method-list",
    ),
    path(
        "/payment-methods/<uuid:alias>",
        PaymentMethodDetailView.as_view(),
        name="payment-method-detail",
    ),
    path(
        "/rent-payments",
        RentPaymentListCreateView.as_view(),
        name="rent-payment-list",
    ),
    path(
        "/rent-payments/<uuid:alias>",
        RentPaymentDetailView.as_view(),
        name="rent-payment-detail",
    ),
    path(
        "/rent-payments/balance-summary",
        RentBalanceSummaryView.as_view(),
        name="rent-balance-summary",
    ),
    path(
        "/rent-payments/rent-statement-pdf",
        RentStatementView.as_view(),
        name="statement-full-year",
    ),
    path(
        "/rent-payments/payment-history",
        PaymentHistoryView.as_view(),
        name="payment-history",
    ),
    path(
        "/property-and-tenancy-details",
        PropertyTenancyListView.as_view(),
        name="property-details",
    ),
    path(
        "/financial-overview",
        FinancialOverviewListView.as_view(),
        name="financial-overview",
    ),
    path(
        "/maintenance-requests",
        MaintenanceRequestListCreateAPIView.as_view(),
        name="maintenance-request-list-create",
    ),
    path(
        "/maintenance-requests/<uuid:alias>",
        MaintenanceRequestRetrieveUpdateDestroyAPIView.as_view(),
        name="maintenance-request-detail",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments",
        MaintenanceRequestCommentListCreateView.as_view(),
        name="maintenance-request-comments",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments/<uuid:comment_alias>",
        MaintenanceRequestCommentRetrieveUpdateDestroyView.as_view(),
        name="maintenance-request-comment-detail",
    ),
    path(
        "/compliance-certificates",
        TenantSharedComplianceListView.as_view(),
        name="tenant-shared-compliance-list",
    ),
    path("/list", TenantListAPiView.as_view(), name="tenant-list"),
]
