# Generated by Django 6.0.6 on 2026-09-02 09:36

from django.db import migrations, connection
from django.db.utils import ProgrammingError


def remove_constraint_if_exists(apps, schema_editor):
    """Remove the constraint if it exists in the database."""
    with connection.cursor() as cursor:
        # Check if constraint exists before trying to remove it
        cursor.execute("""
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'unique_subscription_billing_period_commission'
            AND table_name = 'referral_referralcommission'
        """)
        if cursor.fetchone():
            try:
                cursor.execute("""
                    ALTER TABLE referral_referralcommission 
                    DROP CONSTRAINT unique_subscription_billing_period_commission
                """)
            except ProgrammingError:
                # Constraint doesn't exist or already removed
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_alter_referralcommission_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
    ]
