# Generated by Django 6.0.6 on 2026-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_alter_referralcommission_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referralcommission',
            name='unique_subscription_billing_period_commission',
        ),
    ]
