# Generated by Django 6.0.6 on 2026-09-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_remove_referralcommission_unique_subscription_billing_period_commission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referralcommission',
            name='unique_subscription_billing_period_commission',
        ),
    ]
