# Generated by Django 6.0.6 on 2026-09-07 07:02

from django.db import connection, migrations


def remove_constraint_if_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.table_constraints
            WHERE constraint_name = 'unique_subscription_billing_period_commission'
              AND table_name = 'referral_referralcommission'
            """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE referral_referralcommission
                DROP CONSTRAINT unique_subscription_billing_period_commission
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_remove_referralcommission_unique_subscription_billing_period_commission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='referralcommission',
                    name='unique_subscription_billing_period_commission',
                ),
            ],
        ),
    ]
