# Generated by Django 6.0.6 on 2026-09-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_remove_referralcommission_unique_subscription_billing_period_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadorprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ambassadorprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ambassadorprofile',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='unique_ambassador_invited_email',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='ambassador',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_organisation',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ReferralCommission',
        ),
        migrations.DeleteModel(
            name='AmbassadorProfile',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
