# Generated by Django 6.0.6 on 2026-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
