# Generated by Django 6.0.6 on 2026-09-08 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_rename_current_period_end_organisationsubscription_end_date_and_more'),
        ('subscription', '0006_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('last_four', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=50)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_payment_cards', to='organisation.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organisation',), name='unique_default_card_per_organisation')],
            },
        ),
    ]
