# Generated by Django 6.0.6 on 2026-09-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_paymenttransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
