# Generated by Django 6.0.6 on 2026-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='primary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
