# Generated by Django 6.0.6 on 2026-06-16 10:28

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=common.models.TimestampThumbnailImageField(blank=True, null=True, upload_to='organisation/logo'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='profile_image',
            field=common.models.TimestampThumbnailImageField(blank=True, null=True, upload_to='organisation/profile'),
        ),
        migrations.CreateModel(
            name='OrganisationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('role', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('ORGANISATION_ADVISER', 'Organisation Adviser'), ('ORGANISATION_DIRECTOR', 'Organisation Director'), ('ORGANISATION_ADMIN', 'Organisation Admin')], default='ORGANISATION_ADMIN', max_length=64, null=True, verbose_name='Role')),
                ('designation', models.CharField(blank=True, max_length=128, null=True, verbose_name='Designation')),
                ('official_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Official Email')),
                ('official_phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Official Phone')),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Permanent Address')),
                ('present_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Present Address')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10, verbose_name='Gender')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('source', models.CharField(blank=True, choices=[('GOOGLE', 'Google'), ('SOCIAL_MEDIA', 'Social Media'), ('REFERRAL', 'Referral'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], max_length=255, null=True, verbose_name='Source')),
                ('other_source', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_users', to='organisation.organisation', verbose_name='Organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Organisation User',
                'verbose_name_plural': 'Organisation Users',
                'ordering': ['-created_at', '-updated_at'],
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
