# Generated by Django 6.0.6 on 2026-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_organisation_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='note',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='official_email',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='official_phone',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='other_source',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='organisationuser',
            name='source',
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='role',
            field=models.CharField(blank=True, choices=[('LANDLORD', 'Landlord'), ('ADMIN', 'Admin'), ('LETTING_AGENT', 'Letting Agent')], default='LANDLORD', max_length=64, null=True, verbose_name='Role'),
        ),
    ]
