# Generated by Django 6.0.6 on 2026-08-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_organisationuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
