# Generated by Django 6.0.6 on 2026-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_organisation_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
