# Generated by Django 6.0.6 on 2026-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_organisation_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_access_token_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
