# Generated by Django 6.0.6 on 2026-09-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_organisationsubscription'),
        ('organisation', '0007_organisation_stripe_access_token_encrypted_and_more'),
    ]

    operations = [
    ]
