# Generated by Django 6.0.6 on 2026-09-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_merge_20260902_0453'),
        ('organisation', '0008_processedwebhookevent'),
    ]

    operations = [
    ]
