# Generated by Django 6.0.6 on 2026-09-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_merge_20260903_0552'),
        ('organisation', '0009_merge_20260903_0602'),
    ]

    operations = [
    ]
