# Generated by Django 6.0.6 on 2026-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_merge_20260907_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationsubscription',
            old_name='current_period_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='organisationsubscription',
            old_name='current_period_start',
            new_name='next_billing_date',
        ),
        migrations.RenameField(
            model_name='organisationsubscription',
            old_name='started_at',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProcessedWebhookEvent',
        ),
    ]
