# Generated by Django 6.0.6 on 2026-09-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_merge_20260907_0446'),
        ('organisation', '0011_rename_current_period_end_organisationsubscription_end_date_and_more'),
    ]

    operations = [
    ]
